package component:test-component;

interface resource-interface{
    resource resource-counter{
        constructor();
        do-something: func() -> string;
        add-one: func();
        get-value: func() -> u32;
    }
}

interface logger{
    my-print-log: func(text:string);
}


// Since this is not exported, does not have to be included
// interface resource-get-structure-interface {
//     resource resource-get-structure{
//         constructor();
//         get-structure: func(key:string)->structure;
//     }
// }

/// An example world for the component to target.
world example {
    // Since these interfaces exist locally, import not required
    // import resource-interface;
    // import logger;

    record structure{
        number: u64,
        some-str: string
    }

    export get-structure: func()-> structure;
    export resource-interface;
    export logger;
}
