package component:test-component;

interface resource-interface{
    resource test-resource{
        constructor();
        do-something:func()->string;
        add-one:func();
        get-value: func()->u32;
    }
}

// interface logger{
//     print: func(text:string);
// }

/// An example world for the component to target.
world example {
    record structure{
        number: u64,
        some-str: string
    }

    record something-else{
        s:string
    }

    resource resource-test{
        constructor();
        get-structure: func(key:string)->structure;
    }

    export get-structure: func()-> structure;
    export resource-interface;
    // import logger;
}
